apiVersion: v1
kind: Service
metadata:
  name: platformnpservice-srv
spec:
  type: NodePort
  selector:
    app: platformservice
  ports:
  - name: platformservice
    protocol: TCP
    port: 8001
    targetPort: 8080
    nodePort: 30000 # 클러스터 노드에서 접근 가능한 포트
